---

- name: Disable SELINUX
  selinux: state=disabled
   
- name: Add repository Percona
  yum: 
    name: http://www.percona.com/downloads/percona-release/redhat/0.1-4/percona-release-0.1-4.noarch.rpm
    state: present

- name: Install MySQL Python
  yum:
    name: MySQL-python
    state: latest
    
- name: Install Percona packages
  yum:
    name: Percona-XtraDB-Cluster-full-57
    state: latest
    
- name: Start Percona
  systemd: 
    name: mysql
    state: started

- name: Change root password
  shell: mysqladmin -u root -p$(grep 'temporary password' /var/log/mysqld.log | awk '{print $11}') password '{{ root_percona_password }}'

- name: Setting /etc/hosts
  lineinfile: dest=/etc/hosts line={{ item }}
  with_items:
          - '{{ ip_no01 }} {{ hostname_no01 }}'
          - '{{ ip_no02 }} {{ hostname_no02 }}'
          - '{{ ip_no03 }} {{ hostname_no03 }}'

- name: Add user SST Percona
  mysql_user:
          login_user: root
          login_password: '{{ root_percona_password }}'
          name: sstuser
          password: '{{ sstuser_password }}'
          priv: '*.*:ALL'
  when: inventory_hostname == '{{ ip_no01 }}'

- name: Add user monitor to Keepalived 
  mysql_user:
          login_user: root
          login_password: '{{ root_percona_password }}'
          name: monitor
          password: '{{ monitor_password }}'
  when: inventory_hostname == '{{ ip_no01 }}'

- name: Add user to clustercheck cluster
  mysql_user:
          login_user: root
          login_password: '{{ root_percona_password }}'
          name: clustercheck
          password: '*2470C0C06DEE42FD1618BB99005ADCA2EC9D1E19'
          priv: '*.*:USAGE'
  when: inventory_hostname == '{{ ip_no01 }}'

- name: Stop Percona
  systemd: 
    name: mysql
    state: stopped

- name: Copy template my.cnf
  template: src=my.cnf dest=/etc force=yes

- name: Configure PCS Strict
  lineinfile:
    dest=/etc/percona-xtradb-cluster.conf.d/wsrep.cnf
    regexp='pxc_strict_mode=ENFORCING'
    line='pxc_strict_mode=PERMISSIVE'
    state=present

- name: Start Percona Bootstrat on no01
  systemd:
    name: mysql@bootstrap
    state: started
    enabled: no
  when: inventory_hostname == '{{ ip_no01 }}'

- name: Enable mysql on no01
  systemd:
    name: mysql
    enabled: yes
  when: inventory_hostname == '{{ ip_no01 }}'

- name: Start and enable Percona
  systemd:
    name: mysql
    state: started
    enabled: yes
  when: inventory_hostname == '{{ item }}'
  with_items:
          - '{{ ip_no02 }}'
          - '{{ ip_no03 }}'

- name: Install keepalived
  yum:
    name: keepalived
    state: latest

- name: Copy template keepalived to no01
  template: src=keepalived01.conf dest=/etc/keepalived/keepalived.conf force=yes owner=root group=root
  when: inventory_hostname == '{{ ip_no01 }}'

- name: Copy template keepalived to no02
  template: src=keepalived02.conf dest=/etc/keepalived/keepalived.conf force=yes owner=root group=root
  when: inventory_hostname == '{{ ip_no02 }}'

- name: Copy template keepalived to no03
  template: src=keepalived03.conf dest=/etc/keepalived/keepalived.conf force=yes owner=root group=root
  when: inventory_hostname == '{{ ip_no03 }}'

- name: configure iptables /etc/rc.local
  lineinfile: dest=/etc/rc.local line='$(which iptables) -t nat -A PREROUTING -d {{ keepalived_VIP }} -p tcp -j REDIRECT' owner=root group=root mode=0775
 
- name: Configure iptables
  iptables:
    table: nat
    chain: PREROUTING
    in_interface: '{{ ansible_default_ipv4.interface }}'
    protocol: tcp
    match: tcp
    destination_port: 3306
    destination: '{{ keepalived_VIP }}'
    jump: REDIRECT
    to_ports: 3306
    comment: Redirect MYSQL traffic to host '{{ ansible_default_ipv4.address }}'
  become: yes

- name: Start and enable keepalived
  systemd:
    name: keepalived
    state: started
    enabled: yes
