- name: Instalando pacotes.
  apt: name={{ item }} state=latest install_recommends=yes update_cache=yes
  with_items:
    - "{{ debian_nagios_client_packages }}"
  when: ansible_distribution == 'Debian'

- name: Instalando pacotes
  yum: name={{ item }} state=latest
  with_items:
    - "{{ redhat_nagios_client_packages }}"
  when: ansible_distribution == 'CentOS'

- name: Adicionando group
  group: name=nagios state=present 

- name: Adicionando usuario
  user: name=nagios groups=nagios append=yes

- name: Download Nagios
  get_url: url={{item.url}}  dest=/opt/ validate_certs=no
  with_items: 
    - { url: "https://nagios-plugins.org/download/nagios-plugins-2.2.1.tar.gz" }
    - { url: "https://github.com/NagiosEnterprises/nrpe/archive/nrpe-3.2.0.zip" }

- name: Descompactando Nagios
  unarchive: src=/opt/{{item}} dest=/opt remote_src=True
  with_items:
    - nagios-plugins-2.2.1.tar.gz
    - nrpe-nrpe-3.2.0.zip

- name: Preparando Nagios-plugins
  shell: ./configure --with-nagios-user=nagios --with-nagios-group=nagios
  args: 
    chdir: /opt/nagios-plugins-2.2.1

- name: Compilando Nagios-plugins
  make: chdir=/opt/nagios-plugins-2.2.1 
- make: chdir=/opt/nagios-plugins-2.2.1 target=install

- name: Preparando Nagios-nrpe
  shell: ./configure --with-nrpe-user=nagios --with-nagios-group=nagios --with-init-type=systemd
  args: 
    chdir: /opt/nrpe-nrpe-3.2.0

- name: Compilando Nagios-nrpe
  make: chdir=/opt/nrpe-nrpe-3.2.0 target={{item}}
  with_items:
    - all
    - install
    - install-plugin
    - install-daemon
    - install-config
    - install-init

- name: Copiando template do nrpe.cfg
  template: src=nrpe.cfg dest=/usr/local/nagios/etc/ mode=0644 owner=nagios group=nagios

- name: Copiando arquivos de plugin
  copy: src={{ item }} dest=/usr/local/nagios/libexec/ mode=0755 force=yes owner=nagios group=nagios
  with_items: 
    - check_cpu
    - check_mem

- name: Acertando permissoes
  shell: chown -R nagios:nagios /usr/local/nagios ; chmod -R 755 /usr/local/nagios

- name: Removendo /opt/nagios-plugins-2.2.1 /opt/nrpe-nrpe-3.2.0
  shell: /bin/rm -fr /opt/nagios-plugins-2.2.1 /opt/nrpe-nrpe-3.2.0

- name: Reiniciando servicos
  systemd: state=restarted daemon_reload=yes name={{item}} enabled=True
  with_items:
    - nrpe.service
