#!/bin/bash
 
SMTP_SERVER=""
USER="no-reply@phconsultoria.net.br"
PASSWORD=""
SENDER=""
SUBJECT=$1
RECIPIENTS=$2

/usr/local/bin/sendEmail -s $SMTP_SERVER:587 -o tls=no -xu $USER -xp $PASSWORD -f $SENDER -u $SUBJECT -t $RECIPIENTS
