---

- name: Instalando dependencias
  apt: name=inotify-tools state=latest install_recommends=yes update_cache=yes
  when: ansible_distribution == 'Debian' or ansible_distribution == 'Ubuntu'

- name: Install Packages
  yum: name=inotify-tools state=latest
  when: ansible_distribution == 'CentOS' or ansible_distribution == 'Red Hat Enterprise Linux'

- name: Efetuando download e descompactacao do Maldet Malware Detect
  unarchive: src=https://www.rfxn.com/downloads/maldetect-current.tar.gz dest=/opt remote_src=yes

- name: Renomeando diretorio
  shell: mv maldetect-* maldetect
  args:
          chdir: /opt
          
- name: Realizando a instalacao
  shell: ./install.sh
  args:
          chdir: /opt/maldetect

- name: Removendo fontes de instalacao
  file: path=/opt/maldetect state=absent

- name: Configurando notificacoes por email
  lineinfile: dest=/usr/local/maldetect/conf.maldet state=present regexp={{ item.regexp }} line={{ item.line }}
  with_items:
          - { regexp: 'email_alert="0"', line: 'email_alert="1"' }
          - { regexp: 'email_addr="you@domain.com', line: 'email_addr="{{ email }}"' }

- name: Reiniciando cron
  systemd: name=cron state=restarted
  when: ansible_distribution == 'Debian' or ansible_distribution == 'Ubuntu'

- name: Reiniciando cron
  systemd: name=crond state=restarted
  when: ansible_distribution == 'CentOS' or ansible_distribution == 'Red Hat Enterprise Linux'
