---

#--- Install Bacula packages

- name: Install Bacula packages
  yum: name={{item}} state=latest
  with_items:
      - "{{ bacula_packages }}"

- name: Criando diretorio de backup
  file: path={{item}} state=directory mode=775 owner=root group=root
  with_items:
      - /backup
      - /backup/srvbacula
      - /restore

#--- Install Bacula

- name: Download Bacula source
  get_url: url="http://www.bacula.com.br/atual"  dest=/opt/ validate_certs=no

- name: Descompactando o Bacula
  shell: tar zxf bacula* && rm -rf bacula*.tar.gz && mv bacula* bacula
  args:
      chdir: /opt

- name: Executando o ./configure
  shell: ./configure --with-readline=/usr/include/readline --disable-conio --bindir=/usr/bin --sbindir=/usr/sbin --with-scriptdir=/usr/libexec/bacula/ --with-working-dir=/var/spool/bacula/ --with-logdir=/var/log --enable-smartalloc --with-mysql --with-archivedir=/backup --with-job-email=suporte@phconsultoria.com.br --with-hostname=localhost
  args:
      chdir: /opt/bacula/

- name: Compilando o Bacula
  make: chdir=/opt/bacula target={{item}}
  with_items:
      - install
      - install-autostart

#--- Configure MariaDB

- name: Iniciando MariaDB
  systemd: state=restarted daemon_reload=yes name=mariadb enabled=True

- name: Change permissions on bacula Directory
  file: path=/usr/libexec/bacula/ owner=root group=root mode=0755 recurse=yes

- name: Create user bacula MariaDB
  shell: mysql -h 127.0.0.1 -u root -e "CREATE USER 'bacula'@'localhost' IDENTIFIED BY 'YmFjdWxhCg=='; FLUSH PRIVILEGES;"

- name: Grant privileges user bacula on MariaDB
  shell: mysql -h 127.0.0.1 -u root -e "CREATE DATABASE bacula; GRANT ALL PRIVILEGES ON bacula.* TO 'bacula'@'%'; FLUSH PRIVILEGES;"

- name: Configure Databases bacula
  shell: ./create_bacula_database -u root && ./make_bacula_tables -u root && ./grant_bacula_privileges -u root
  args:
      chdir: /usr/libexec/bacula

- name: Criando copia de seguranca do Bacula
  command: mv /etc/bacula /etc/bacula_original

- name: Copiando arquivos Bacula (modelo)
  copy: src=bacula.tar.xz dest=/etc 

- name: Copiando arquivos sendEmail
  copy: src=sendEmail dest=/usr/local/bin

- name: Copiando arquivos sendEmail-bacula
  copy: src=sendEmail-bacula dest=/usr/local/bin

- name: Ajustando permissoes sendEmail
  file: path={{item}} owner=root group=root mode=0755
  with_items:
      - /usr/local/bin/sendEmail
      - /usr/local/bin/sendEmail-bacula

- name: Descompactando Bacula
  shell: tar Jxf bacula.tar.xz && rm -rf bacula.tar.xz
  args:
      chdir: /etc

- name: Ajustando permissoes diretorio Bacula
  file: path=/etc/bacula owner=root group=root recurse=yes

#--- Start services

- name: Iniciando Bacula Server
  systemd: state=restarted daemon_reload=yes name={{item}} enabled=True
  with_items:
      - bacula-sd
      - bacula-dir
      - bacula-fd
