---

#--- General ---#

- name: Add nameserver to resolv.conf
  lineinfile: dest=/etc/resolv.conf line='nameserver {{ dns_server }}' insertbefore=BOF state=present

#---Add repository ---#

- name: Setup repository APT key
  apt_key: url=http://repo.pbis.beyondtrust.com/apt/RPM-GPG-KEY-pbis state=present
  when: ansible_distribution == 'Debian' or ansible_distribution == 'Ubuntu'
           
- name: Setup PBIS repository
  get_url: url=http://repo.pbis.beyondtrust.com/apt/pbiso.list  dest=/etc/apt/sources.list.d/pbiso.list mode=0640
  when: ansible_distribution == 'Debian' or ansible_distribution == 'Ubuntu'

- name: Download pbiso repo
  get_url: url=http://repo.pbis.beyondtrust.com/yum/pbiso.repo dest=/etc/yum.repos.d/pbiso.repo mode=0644
  when: ansible_distribution == 'CentOS' or ansible_distribution == 'Red Hat Enterprise Linux'
 
- name: Update System
  yum: name=* state=latest update_cache=yes
  when: ansible_distribution == 'CentOS' or ansible_distribution == 'Red Hat Enterprise Linux'
 
- name: Install Packages
  apt: name={{ pbis_packages_debian }} state=latest update_cache=yes
  when: ansible_distribution == 'Debian' or ansible_distribution == 'Ubuntu'

- name: Install pbis enterprise
  yum: name={{ pbis_packages_redhat }} state=latest
  when: ansible_distribution == 'CentOS' or ansible_distribution == 'Red Hat Enterprise Linux'

#--- Join on domain

- name: Check if server is joined to the domain
  command: /opt/pbis/bin/lsa get-status
  register: domain_member

- name: Join domain
  shell: /opt/pbis/bin/domainjoin-cli join {{ ad_domain }} {{ ad_user }} {{ ad_password }}
  when: '"Online" not in domain_member'
   
- name: Configure PBIS LogInvalidPass
  shell: /opt/pbis/bin/config LogInvalidPasswords true
  ignore_errors: yes

- name: Configure PBIS AssumeDefaultDomain
  shell: /opt/pbis/bin/config AssumeDefaultDomain true
  ignore_errors: yes

- name: Configure PBIS LoginShellTemplate
  shell: /opt/pbis/bin/config LoginShellTemplate /bin/bash
  ignore_errors: yes

- name: Configure PBIS RequireMembershipOf
  shell: /opt/pbis/bin/config RequireMembershipOf {{ ad_netbios }}\\{{ sudo_group }}

- name: Adicionar usuario admin_anima no sudo
  lineinfile:
          dest=/etc/sudoers
          line='%{{ sudo_group }} ALL=(ALL) ALL'
